version: '2.1'
networks:
  default: # to make compose work together with openvpn on linux
    ipam:
      config:
        - subnet: 10.154.0.0/24
          gateway: 10.154.0.1
services:
 lab:
   user: $UID
   container_name: lab
   build: ./dsb2019/dsb2019
   command: /code/run_lab.sh
   environment:
    - LOCAL_LAB_ENV=1
   volumes:
     - ./:/code
   expose:
     - "8888"
   ports:
     - "8888:8888"
 tests:
   user: $UID
   container_name: tests
   build: ./dsb2019/dsb2019
   command: /code/run_tests.sh
   volumes:
     - ./:/code